#!/usr/bin/env ruby
require "rubygems"
require "thor"

require File.expand_path("../../generators/integration_generator", __FILE__)

Dir[File.expand_path("../..", __FILE__) + "/generators/*.rb"].each do |generator|
  require generator
end

class Generate < Thor
  register(IntegrationGenerator, "integration", "integration NAME", "Generates a new integration.")
end

Generate.start
